# Generated by Django 4.0.2 on 2022-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
