# Generated by Django 4.0.2 on 2022-02-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
