# Generated by Django 4.0.2 on 2022-02-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('image', models.FilePathField(blank=True, default=None, null=True, path='C:\\Development\\mwilliamson_portfolio_python\\mwilliamson_portfolio_python\\img')),
            ],
        ),
    ]
